### ISSUE TITLE
Support multi-call

### ISSUE THREAD

**Issue by notdanilo** [sensorial-systems/agents#1]
1. Assign a function to an Agent
2. Ask it to run it 5 times
3. Agent runs it 5 times

**Comment by notdanilo** [comment]
examples/function.rs has an example of multicall support.

It should be included by default (or maybe with some simple setup to switch it on and off)

**Comment by uptudev** [comment]
lmao turning off multicall for the `examples/function.rs` via my implementation of this makes the customer answer their own question :laughing: 

![image](https://github.com/sensorial-systems/agents/assets/91502176/62114bfc-5796-47c2-b0c2-a73a8a8f795c)

**Comment by notdanilo** [comment]
lol that's because the function call is sent back to the user instead of being processed by the assisant's function. I will fix that when the I internalize the multicalls function

**Comment by uptudev** [comment]
I actually got it fixed now on my end with some slight tweaks. I'll open a PR.

![image](https://github.com/sensorial-systems/agents/assets/91502176/f87bb345-bb99-4c8e-9662-fd3db77f86da)
